export enum CategoryEnum {
  Arts = 1,
  Business = 2,
  Comedy = 3,
  Education = 4,
  Fiction = 5,
  Government = 6,
  History = 7,
  HealthAndFitness = 8,
  KidsAndFamily = 9,
  Leisure = 10,
  Music = 11,
  News = 12,
  ReligionAndSpirituality = 13,
  Science = 14,
  SocietyAndCulture = 15,
  Sports = 16,
  Technology = 17,
  TrueCrime = 18,
  TVAndFilm = 19,
  Books = 20,
  Design = 21,
  FashionAndBeauty = 22,
  Food = 23,
  PerformingArts = 24,
  VisualArts = 25,
  Careers = 26,
  Entrepreneurship = 27,
  Investing = 28,
  Management = 29,
  Marketing = 30,
  NonProfit = 31,
  ComedyInterviews = 32,
  Improv = 33,
  StandUp = 34,
  Courses = 35,
  HowTo = 36,
  LanguageLearning = 37,
  SelfImprovement = 38,
  ComedyFiction = 39,
  Drama = 40,
  ScienceFiction = 41,
  AlternativeHealth = 42,
  Fitness = 43,
  Medicine = 44,
  MentalHealth = 45,
  Nutrition = 46,
  Sexuality = 47,
  EducationForKids = 48,
  Parenting = 49,
  PetsAndAnimals = 50,
  StoriesForKids = 51,
  AnimationAndManga = 52,
  Automotive = 53,
  Aviation = 54,
  Crafts = 55,
  Games = 56,
  Hobbies = 57,
  HomeAndGarden = 58,
  VideoGames = 59,
  MusicCommentary = 60,
  MusicHistory = 61,
  MusicInterviews = 62,
  BusinessNews = 63,
  DailyNews = 64,
  EntertainmentNews = 65,
  NewsCommentary = 66,
  Politics = 67,
  SportsNews = 68,
  TechNews = 69,
  Buddhism = 70,
  Christianity = 71,
  Hinduism = 72,
  Islam = 73,
  Judaism = 74,
  Religion = 75,
  Spirituality = 76,
  Astronomy = 77,
  Chemistry = 78,
  EarthSciences = 79,
  LifeSciences = 80,
  Mathematics = 81,
  NaturalSciences = 82,
  Nature = 83,
  Physics = 84,
  SocialSciences = 85,
  Documentary = 86,
  PersonalJournals = 87,
  Philosophy = 88,
  PlacesAndTravel = 89,
  Relationships = 90,
  Baseball = 91,
  Basketball = 92,
  Cricket = 93,
  FantasySports = 94,
  Football = 95,
  Golf = 96,
  Hockey = 97,
  Rugby = 98,
  Running = 99,
  Soccer = 100,
  Swimming = 101,
  Tennis = 102,
  Volleyball = 103,
  Wilderness = 104,
  Wrestling = 105,
  AfterShows = 106,
  FilmHistory = 107,
  FilmInterviews = 108,
  FilmReviews = 109,
  TVReviews = 110
}

export function getCategoryEnumValue(input: string | null): CategoryEnum | null {
  const sanitizedInput = input?.toLowerCase()
    .replace(/\s+/g, '')
    .replace(/[^a-z0-9]/g, '');

  const mapping: { [key: string]: CategoryEnum } = {
    arts: CategoryEnum.Arts,
    books: CategoryEnum.Books,
    design: CategoryEnum.Design,
    fashionandbeauty: CategoryEnum.FashionAndBeauty,
    food: CategoryEnum.Food,
    performingarts: CategoryEnum.PerformingArts,
    visualarts: CategoryEnum.VisualArts,
    business: CategoryEnum.Business,
    careers: CategoryEnum.Careers,
    entrepreneurship: CategoryEnum.Entrepreneurship,
    investing: CategoryEnum.Investing,
    management: CategoryEnum.Management,
    marketing: CategoryEnum.Marketing,
    nonprofit: CategoryEnum.NonProfit,
    comedy: CategoryEnum.Comedy,
    comedyinterviews: CategoryEnum.ComedyInterviews,
    improv: CategoryEnum.Improv,
    standup: CategoryEnum.StandUp,
    education: CategoryEnum.Education,
    courses: CategoryEnum.Courses,
    howto: CategoryEnum.HowTo,
    languagelearning: CategoryEnum.LanguageLearning,
    selfimprovement: CategoryEnum.SelfImprovement,
    fiction: CategoryEnum.Fiction,
    comedyfiction: CategoryEnum.ComedyFiction,
    drama: CategoryEnum.Drama,
    sciencefiction: CategoryEnum.ScienceFiction,
    government: CategoryEnum.Government,
    history: CategoryEnum.History,
    healthandfitness: CategoryEnum.HealthAndFitness,
    alternativehealth: CategoryEnum.AlternativeHealth,
    fitness: CategoryEnum.Fitness,
    medicine: CategoryEnum.Medicine,
    mentalhealth: CategoryEnum.MentalHealth,
    nutrition: CategoryEnum.Nutrition,
    sexuality: CategoryEnum.Sexuality,
    kidsandfamily: CategoryEnum.KidsAndFamily,
    educationforkids: CategoryEnum.EducationForKids,
    parenting: CategoryEnum.Parenting,
    petsandanimals: CategoryEnum.PetsAndAnimals,
    storiesforkids: CategoryEnum.StoriesForKids,
    leisure: CategoryEnum.Leisure,
    animationandmanga: CategoryEnum.AnimationAndManga,
    automotive: CategoryEnum.Automotive,
    aviation: CategoryEnum.Aviation,
    crafts: CategoryEnum.Crafts,
    games: CategoryEnum.Games,
    hobbies: CategoryEnum.Hobbies,
    homeandgarden: CategoryEnum.HomeAndGarden,
    videogames: CategoryEnum.VideoGames,
    music: CategoryEnum.Music,
    musiccommentary: CategoryEnum.MusicCommentary,
    musichistory: CategoryEnum.MusicHistory,
    musicinterviews: CategoryEnum.MusicInterviews,
    news: CategoryEnum.News,
    businessnews: CategoryEnum.BusinessNews,
    dailynews: CategoryEnum.DailyNews,
    entertainmentnews: CategoryEnum.EntertainmentNews,
    newscommentary: CategoryEnum.NewsCommentary,
    politics: CategoryEnum.Politics,
    sportsnews: CategoryEnum.SportsNews,
    technews: CategoryEnum.TechNews,
    religionandspirituality: CategoryEnum.ReligionAndSpirituality,
    buddhism: CategoryEnum.Buddhism,
    christianity: CategoryEnum.Christianity,
    hinduism: CategoryEnum.Hinduism,
    islam: CategoryEnum.Islam,
    judaism: CategoryEnum.Judaism,
    religion: CategoryEnum.Religion,
    spirituality: CategoryEnum.Spirituality,
    science: CategoryEnum.Science,
    astronomy: CategoryEnum.Astronomy,
    chemistry: CategoryEnum.Chemistry,
    earthsciences: CategoryEnum.EarthSciences,
    lifesciences: CategoryEnum.LifeSciences,
    mathematics: CategoryEnum.Mathematics,
    naturalsciences: CategoryEnum.NaturalSciences,
    nature: CategoryEnum.Nature,
    physics: CategoryEnum.Physics,
    socialsciences: CategoryEnum.SocialSciences,
    societyandculture: CategoryEnum.SocietyAndCulture,
    documentary: CategoryEnum.Documentary,
    personaljournals: CategoryEnum.PersonalJournals,
    philosophy: CategoryEnum.Philosophy,
    placesandtravel: CategoryEnum.PlacesAndTravel,
    relationships: CategoryEnum.Relationships,
    sports: CategoryEnum.Sports,
    baseball: CategoryEnum.Baseball,
    basketball: CategoryEnum.Basketball,
    cricket: CategoryEnum.Cricket,
    fantasysports: CategoryEnum.FantasySports,
    football: CategoryEnum.Football,
    golf: CategoryEnum.Golf,
    hockey: CategoryEnum.Hockey,
    rugby: CategoryEnum.Rugby,
    running: CategoryEnum.Running,
    soccer: CategoryEnum.Soccer,
    swimming: CategoryEnum.Swimming,
    tennis: CategoryEnum.Tennis,
    volleyball: CategoryEnum.Volleyball,
    wilderness: CategoryEnum.Wilderness,
    wrestling: CategoryEnum.Wrestling,
    technology: CategoryEnum.Technology,
    truecrime: CategoryEnum.TrueCrime,
    tvandfilm: CategoryEnum.TVAndFilm,
    aftershows: CategoryEnum.AfterShows,
    filmhistory: CategoryEnum.FilmHistory,
    filminterviews: CategoryEnum.FilmInterviews,
    filmreviews: CategoryEnum.FilmReviews,
    tvreviews: CategoryEnum.TVReviews
  };

  return (sanitizedInput && mapping[sanitizedInput]) || null;
}
