export enum CategoryEnum {
  Arts = 1,
  Books = 2,
  Design = 3,
  FashionAndBeauty = 4,
  Food = 5,
  PerformingArts = 6,
  VisualArts = 7,
  Business = 8,
  Careers = 9,
  Entrepreneurship = 10,
  Investing = 11,
  Management = 12,
  Marketing = 13,
  NonProfit = 14,
  Comedy = 15,
  ComedyInterviews = 16,
  Improv = 17,
  StandUp = 18,
  Education = 19,
  Courses = 20,
  HowTo = 21,
  LanguageLearning = 22,
  SelfImprovement = 23,
  Fiction = 24,
  ComedyFiction = 25,
  Drama = 26,
  ScienceFiction = 27,
  Government = 28,
  History = 29,
  HealthAndFitness = 30,
  AlternativeHealth = 31,
  Fitness = 32,
  Medicine = 33,
  MentalHealth = 34,
  Nutrition = 35,
  Sexuality = 36,
  KidsAndFamily = 37,
  EducationForKids = 38,
  Parenting = 39,
  PetsAndAnimals = 40,
  StoriesForKids = 41,
  Leisure = 42,
  AnimationAndManga = 43,
  Automotive = 44,
  Aviation = 45,
  Crafts = 46,
  Games = 47,
  Hobbies = 48,
  HomeAndGarden = 49,
  VideoGames = 50,
  Music = 51,
  MusicCommentary = 52,
  MusicHistory = 53,
  MusicInterviews = 54,
  News = 55,
  BusinessNews = 56,
  DailyNews = 57,
  EntertainmentNews = 58,
  NewsCommentary = 59,
  Politics = 60,
  SportsNews = 61,
  TechNews = 62,
  ReligionAndSpirituality = 63,
  Buddhism = 64,
  Christianity = 65,
  Hinduism = 66,
  Islam = 67,
  Judaism = 68,
  Religion = 69,
  Spirituality = 70,
  Science = 71,
  Astronomy = 72,
  Chemistry = 73,
  EarthSciences = 74,
  LifeSciences = 75,
  Mathematics = 76,
  NaturalSciences = 77,
  Nature = 78,
  Physics = 79,
  SocialSciences = 80,
  SocietyAndCulture = 81,
  Documentary = 82,
  PersonalJournals = 83,
  Philosophy = 84,
  PlacesAndTravel = 85,
  Relationships = 86,
  Sports = 87,
  Baseball = 88,
  Basketball = 89,
  Cricket = 90,
  FantasySports = 91,
  Football = 92,
  Golf = 93,
  Hockey = 94,
  Rugby = 95,
  Running = 96,
  Soccer = 97,
  Swimming = 98,
  Tennis = 99,
  Volleyball = 100,
  Wilderness = 101,
  Wrestling = 102,
  Technology = 103,
  TrueCrime = 104,
  TVAndFilm = 105,
  AfterShows = 106,
  FilmHistory = 107,
  FilmInterviews = 108,
  FilmReviews = 109,
  TVReviews = 110
}

export function getCategoryEnumValue(input: string | null): CategoryEnum | null {
  const sanitizedInput = input?.toLowerCase()
    .replace(/\s+/g, '')
    .replace(/[^a-z0-9]/g, '');

  const mapping: { [key: string]: CategoryEnum } = {
    arts: CategoryEnum.Arts,
    books: CategoryEnum.Books,
    design: CategoryEnum.Design,
    fashionandbeauty: CategoryEnum.FashionAndBeauty,
    food: CategoryEnum.Food,
    performingarts: CategoryEnum.PerformingArts,
    visualarts: CategoryEnum.VisualArts,
    business: CategoryEnum.Business,
    careers: CategoryEnum.Careers,
    entrepreneurship: CategoryEnum.Entrepreneurship,
    investing: CategoryEnum.Investing,
    management: CategoryEnum.Management,
    marketing: CategoryEnum.Marketing,
    nonprofit: CategoryEnum.NonProfit,
    comedy: CategoryEnum.Comedy,
    comedyinterviews: CategoryEnum.ComedyInterviews,
    improv: CategoryEnum.Improv,
    standup: CategoryEnum.StandUp,
    education: CategoryEnum.Education,
    courses: CategoryEnum.Courses,
    howto: CategoryEnum.HowTo,
    languagelearning: CategoryEnum.LanguageLearning,
    selfimprovement: CategoryEnum.SelfImprovement,
    fiction: CategoryEnum.Fiction,
    comedyfiction: CategoryEnum.ComedyFiction,
    drama: CategoryEnum.Drama,
    sciencefiction: CategoryEnum.ScienceFiction,
    government: CategoryEnum.Government,
    history: CategoryEnum.History,
    healthandfitness: CategoryEnum.HealthAndFitness,
    alternativehealth: CategoryEnum.AlternativeHealth,
    fitness: CategoryEnum.Fitness,
    medicine: CategoryEnum.Medicine,
    mentalhealth: CategoryEnum.MentalHealth,
    nutrition: CategoryEnum.Nutrition,
    sexuality: CategoryEnum.Sexuality,
    kidsandfamily: CategoryEnum.KidsAndFamily,
    educationforkids: CategoryEnum.EducationForKids,
    parenting: CategoryEnum.Parenting,
    petsandanimals: CategoryEnum.PetsAndAnimals,
    storiesforkids: CategoryEnum.StoriesForKids,
    leisure: CategoryEnum.Leisure,
    animationandmanga: CategoryEnum.AnimationAndManga,
    automotive: CategoryEnum.Automotive,
    aviation: CategoryEnum.Aviation,
    crafts: CategoryEnum.Crafts,
    games: CategoryEnum.Games,
    hobbies: CategoryEnum.Hobbies,
    homeandgarden: CategoryEnum.HomeAndGarden,
    videogames: CategoryEnum.VideoGames,
    music: CategoryEnum.Music,
    musiccommentary: CategoryEnum.MusicCommentary,
    musichistory: CategoryEnum.MusicHistory,
    musicinterviews: CategoryEnum.MusicInterviews,
    news: CategoryEnum.News,
    businessnews: CategoryEnum.BusinessNews,
    dailynews: CategoryEnum.DailyNews,
    entertainmentnews: CategoryEnum.EntertainmentNews,
    newscommentary: CategoryEnum.NewsCommentary,
    politics: CategoryEnum.Politics,
    sportsnews: CategoryEnum.SportsNews,
    technews: CategoryEnum.TechNews,
    religionandspirituality: CategoryEnum.ReligionAndSpirituality,
    buddhism: CategoryEnum.Buddhism,
    christianity: CategoryEnum.Christianity,
    hinduism: CategoryEnum.Hinduism,
    islam: CategoryEnum.Islam,
    judaism: CategoryEnum.Judaism,
    religion: CategoryEnum.Religion,
    spirituality: CategoryEnum.Spirituality,
    science: CategoryEnum.Science,
    astronomy: CategoryEnum.Astronomy,
    chemistry: CategoryEnum.Chemistry,
    earthsciences: CategoryEnum.EarthSciences,
    lifesciences: CategoryEnum.LifeSciences,
    mathematics: CategoryEnum.Mathematics,
    naturalsciences: CategoryEnum.NaturalSciences,
    nature: CategoryEnum.Nature,
    physics: CategoryEnum.Physics,
    socialsciences: CategoryEnum.SocialSciences,
    societyandculture: CategoryEnum.SocietyAndCulture,
    documentary: CategoryEnum.Documentary,
    personaljournals: CategoryEnum.PersonalJournals,
    philosophy: CategoryEnum.Philosophy,
    placesandtravel: CategoryEnum.PlacesAndTravel,
    relationships: CategoryEnum.Relationships,
    sports: CategoryEnum.Sports,
    baseball: CategoryEnum.Baseball,
    basketball: CategoryEnum.Basketball,
    cricket: CategoryEnum.Cricket,
    fantasysports: CategoryEnum.FantasySports,
    football: CategoryEnum.Football,
    golf: CategoryEnum.Golf,
    hockey: CategoryEnum.Hockey,
    rugby: CategoryEnum.Rugby,
    running: CategoryEnum.Running,
    soccer: CategoryEnum.Soccer,
    swimming: CategoryEnum.Swimming,
    tennis: CategoryEnum.Tennis,
    volleyball: CategoryEnum.Volleyball,
    wilderness: CategoryEnum.Wilderness,
    wrestling: CategoryEnum.Wrestling,
    technology: CategoryEnum.Technology,
    truecrime: CategoryEnum.TrueCrime,
    tvandfilm: CategoryEnum.TVAndFilm,
    aftershows: CategoryEnum.AfterShows,
    filmhistory: CategoryEnum.FilmHistory,
    filminterviews: CategoryEnum.FilmInterviews,
    filmreviews: CategoryEnum.FilmReviews,
    tvreviews: CategoryEnum.TVReviews
  };

  return (sanitizedInput && mapping[sanitizedInput]) || null;
}
