import { DTOChannelAbout } from "./channelAbout";
import { DTOChannelCategory } from "./channelCategory";
import { DTOChannelChat } from "./channelChat";
import { DTOChannelDescription } from "./channelDescription";
import { DTOChannelFunding } from "./channelFunding";
import { DTOChannelImage } from "./channelImage";
import { DTOChannelInternalSettings } from "./channelInternalSettings";
import { DTOChannelLicense } from "./channelLicense";
import { DTOChannelLocation } from "./channelLocation";
import { DTOChannelPerson } from "./channelPerson";
import { DTOChannelPodroll } from "./channelPodroll";
import { DTOChannelPublisher } from "./channelPublisher";
import { DTOChannelRemoteItem } from "./channelRemoteItem";
import { DTOChannelSeason } from "./channelSeason";
import { DTOChannelSocialInteract } from "./channelSocialInteract";
import { DTOChannelTrailer } from "./channelTrailer";
import { DTOChannelTxt } from "./channelTxt";
import { DTOChannelValue } from "./channelValue";
import { DTOFeed } from "../feed/feed";

export interface DTOChannel {
  id: number;
  id_text: string;
  slug: string | null;
  feed_id: number;
  podcast_index_id: number;
  podcast_guid: string | null;
  title: string | null;
  sortable_title: string | null;
  medium_id: number | null;
  has_podcast_index_value: boolean;
  has_value_time_splits: boolean;
  feed?: DTOFeed;
  channel_about?: DTOChannelAbout;
  channel_categories?: DTOChannelCategory[];
  channel_chat?: DTOChannelChat;
  channel_description?: DTOChannelDescription;
  channel_fundings?: DTOChannelFunding[];
  channel_images?: DTOChannelImage[];
  channel_internal_settings?: DTOChannelInternalSettings;
  channel_license?: DTOChannelLicense;
  channel_location?: DTOChannelLocation;
  channel_persons?: DTOChannelPerson[];
  channel_podroll?: DTOChannelPodroll;
  channel_publisher?: DTOChannelPublisher;
  channel_remote_items?: DTOChannelRemoteItem[];
  channel_seasons?: DTOChannelSeason[];
  channel_social_interacts?: DTOChannelSocialInteract[];
  channel_trailers?: DTOChannelTrailer[];
  channel_txts?: DTOChannelTxt[];
  channel_values?: DTOChannelValue[];
}
